export const USER_LOCALSTORAGE_TOKEN = 'USER_LOCALSTORAGE_TOKEN';
export const USER_LOCALSTORAGE_REFRESH = 'USER_LOCALSTORAGE_REFRESH';
export const USER_LOCALSTORAGE_ID = 'USER_LOCALSTORAGE_ID';
export const USER_COURSE_ID = 'USER_COURSE_ID';